name: mahalanobis
channels:
        - conda-forge
        - pytorch
dependencies:
        - python
        - pip
        - plotly
        - numpy
        - scipy
        - jupyterlab
        - pytorch
        - torchvision
        - cpuonly
        - pytorch-lightning
        - pytest
        - black
        - scikit-learn
        - pandas
        - statsmodels